name: Actualizacion Masiva CSV a JSON
on:
  schedule:
    - cron: '0 */12 * * *' # Cada 12 horas
  workflow_dispatch: # Permite ejecución manual desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests pandas

      - name: Ejecutar Descarga y Conversion
        run: python scraper.py

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data_*.json
          git commit -m "Sincronizacion automatica de datos MEF" || echo "Sin cambios"
          git push
