name: Actualizacion Masiva de Datos MEF

on:
  schedule:
    - cron: '0 */12 * * *' # Cada 12 horas
  workflow_dispatch: # Botón para ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependencias
        run: pip install pandas requests

      - name: Ejecutar Descarga Cruda
        run: python scraper.py

      - name: Guardar cambios en GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          
          # Solo agregamos los archivos que el scraper SI está generando
          git add data_situacion.json data_f12b.json
          
          # Hacemos el commit. Si no hay cambios, no fallará.
          git commit -m "Update Situacion y F12B: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
